### PR TITLE
Insert as Tag: OS X keybinding update

### PR DESCRIPTION
**Pull request by star-szr**
Previous keybinding was not working for me.

### CODE REVIEW

**Comment by titoBouzout** [comment]
Ok thanks!

**Comment by star-szr** [comment]
I was just looking through the other pull requests, you may want to try this keybinding on Windows as well.
https://github.com/SublimeText/Tag/pull/8#issuecomment-3373546

**Comment by titoBouzout** [comment]
Update the bindings for Windows and Linux too.
https://github.com/SublimeText/Tag/commit/c7d104f43ad6ad786158f20d14fae30c043bce7f

**Comment by sen-zo** [comment]
Sorry for intervening here, but i think it doesn't make much sense to change this keybinding. In TextMate there was the shortcut ctrl+< for this command. The hole point of this command (InsertAsTag) is to reproduce this behavior for those Users who are used to use this shortcut. The InsertAsTag command doesn't invent anything new which isn't already implemented in ST2: If you write for example "div" and press TAB you will get `<div></div>`, the same result as with InsertAsTag. The other thing it does is inserting an empty p-tag with the p preselected if there is no current word. This can also be achieved with ctrl+shift+w. So as i said, the hole point is to give the ctrl+< shortcut to those who are used to it. 

It looks like this should be better explained in the readme file - my fault.

By the way, for me ctrl+< is working on my Mac (ctrl+shift+, is used by ZenCoding).

Please see this post too: http://www.sublimetext.com/forum/viewtopic.php?f=2&t=3552

**Comment by star-szr** [comment]
@sen-zo - No need to apologize. On my keyboard layout (US English), the key binding of "ctrl+shift+," is exactly equivalent to "ctrl+<". It works in exactly the same way as the TextMate shortcut. The "ctrl+<" key binding did not work at all on either of my OS X machines, I can't speak to Windows or Linux. Both machines are running the latest dev build of ST2 and OS X 10.6.8.

**Comment by titoBouzout** [comment]
An idea: Maybe we can add both key binding. If one is not working "ctrl+<" you can use ctrl+shift+,

**Comment by sen-zo** [comment]
@Cottser: That makes it clear, on my keyboard layout (german) the two shortcuts have absolutely nothing in common ;) In this case the US_en layout is more important and can be overwritten if needed. 

Do you have ZenCoding installed? It also has "ctrl+shift+," defined, maybe this is the problem?

Could you define both shortcuts as Tito suggested and see if it works for you than?

Thanks

**Comment by star-szr** [comment]
I don't have ZenCoding installed. If it's just me having this issue, I can override this in my own key bindings, but I'm assuming it's everyone on a US keyboard layout. Not sure the best way to handle this :)

**Comment by star-szr** [comment]
Another thought: Sublime should probably work as expected with "ctrl+<", and the "ctrl+shift+," was really a workaround. Maybe this should be submitted as a bug/feature request to Jon?

For now, I think the shortcut should be reverted to "ctrl+<", and a note added to the readme with the "ctrl+shift+," binding ready to copy and paste with brief instructions.

**Comment by sen-zo** [comment]
The US keyboard layout is the most important so the key binding should stay like it currently is, maybe with an explanation in the readme. I will submit the bug/feature request. When it gets addressed we can change the shortcut.

**Comment by titoBouzout** [comment]
Guys, feel free to take the action is appropriated.

**Comment by star-szr** [comment]
I agree with @sen-zo that the US keyboard layout is probably the most important, so for now we should update the readme to indicate that non-US keyboard layouts may need to change the shortcut to "ctrl+<".

**Pull request merged**
